name: album_share
description: "An unofficial Immich client focused on album sharing."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  another_flushbar: ^1.12.30
  bitsdojo_window: ^0.1.6
  cookie_jar: ^4.0.8
  dio: ^5.4.3+1
  dio_cookie_manager: ^3.1.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  form_field_validator: ^1.1.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  logging: ^1.2.0
  path_provider: ^2.1.3
  sentry_logging: ^8.3.0
  vrouter: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.11
  riverpod_lint: ^2.1.1
  # analyzer: ^5.13.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/logo_borderless.png
