name: album_share
description: "An unofficial Immich client focused on album sharing."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  another_flushbar: ^1.12.30
  bitsdojo_window: ^0.1.6
  cached_network_image: ^3.3.1
  collection: ^1.18.0
  cookie_jar: ^4.0.8
  dio: ^5.4.3+1
  dio_cookie_manager: ^3.1.1
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  flutter_cache_manager: ^3.3.2
  flutter_displaymode: ^0.6.0
  flutter_riverpod: ^2.5.1
  form_field_validator: ^1.1.0
  intl: any
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  logging: ^1.2.0
  octo_image: ^2.0.0
  path_provider: ^2.1.3
  scrollable_positioned_list: ^0.3.8
  # sentry_logging: ^8.3.0
  thumbhash: ^0.1.0+1
  video_player:
    path: './video_player'
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8
  go_router: ^14.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.11
  riverpod_lint: ^2.1.1
  flutter_native_splash: ^2.4.1
  flutter_launcher_icons: ^0.13.1
  # analyzer: ^5.13.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
  generate: true # localizations

flutter_native_splash:
  color: "#ead1dc"
  color_dark: "#000000"
  image: assets/logo-splash.png
  android_12:
    image: assets/logo-splash-android12.png

flutter_launcher_icons:
  image_path_android: 'assets/logo-large.png'
  adaptive_icon_background: '#ffffff'
  adaptive_icon_foreground: 'assets/logo-android-adaptive.png'
  image_path_ios: 'assets/logo-large-white.png'
  android: 'ic_launcher'
  ios: false
  remove_alpha_ios: true