name: Update version tag after merge into 'Deployment'

on:
  push:
    branches:
      - main

jobs:
  update-version-tag:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Parse pubspec.yaml
        id: yaml-version
        uses: pietrobolcato/action-read-yaml@1.0.0
        with:
            config: pubspec.yaml

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          tag: "v${{ steps.yaml-version.outputs['version'] }}"
          commit: "master"
          token: ${{ secrets.GITHUB_TOKEN }}